### ISSUE TITLE
First test not accurately testing that old createClass syntax is being used

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/react-components-lab#5]
Test uses `OlderCoaster.name` to determine if ES2015 is being used or not. 

Solution is uses `const OlderCoaster = React.createClass({` to try and pass this, but error still throws that `Error: The`Oldercoaster`component is being created using a ES2015 class.`. It appears this is not a good way to test that student is using `React.createClass()`

**Comment by kwebster2** [comment]
@aturkewi the test has not yet been updated - Dakota has submitted a pull request to fix it. Had a student encounter the issue in the v-000 track as well.
